### ISSUE TITLE
simpleviewer example does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [piotrbetlej/qimagegrabber#3]
```
The simpleviewer example does not appear to work.
When I connect to an mjpeg stream from an IP camera it may say
start reading image 
reading image done 
but the image is corrupt (just a few lines of random colour dots)
and it doesn't continuously refresh.


```

Original issue reported on code.google.com by `a...@sat.dundee.ac.uk` on 3 Dec 2013 at 3:16

**Comment by piotrbetlej** [comment]
MJPEG stream parsing is fully functional now. Problem was readLine() function used for QNetworkReply (derived from QIODevice) data read. It is not suitable for reading binary data and works just for pure ASCII strings, returning otherwise random byte responses.
